name: Build ISO

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build ISO in Arch Linux Container
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace archlinux:latest bash -c "
          pacman -Sy --noconfirm archiso git make
          make build || echo 'Build needs configuration'
        "
    
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: hades-os-iso
        path: releases/*.iso
        retention-days: 7
