name: Build ISO

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y archiso git
    
    - name: Build ISO
      run: make build
    
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v3
      with:
        name: hades-os-iso
        path: releases/*.iso
